import java.util.regex.Matcher

apply plugin: 'java'
apply plugin: 'jacoco'

sourceCompatibility = 1.8
targetCompatibility = 1.8
version = '1.0'
[compileJava, compileTestJava, javadoc]*.options*.encoding = 'UTF-8'

repositories {
    mavenCentral()
}

jacocoTestReport {
    reports {
        xml.enabled true
        html.enabled false
    }
}

dependencies {
    implementation 'commons-codec:commons-codec:1.15'
    implementation group: 'com.squareup.okhttp3', name: 'okhttp', version: '4.9.3'
    implementation 'com.google.code.gson:gson:2.9.0'
//    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.1'
//    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.7.1'
    testImplementation group: 'junit', name: 'junit', version: '4.12'
}

test {
//    useJUnitPlatform()
    useJUnit()  // JUnit 4
}

task unitTest(type: Test) {
    useJUnitPlatform {
        includeTags 'UnitTest'
    }
}

task getHomeDir {
    doLast {
        println gradle.gradleHomeDir
    }
}

apply plugin: 'checkstyle'

task apiJavadocs(type: Javadoc) {
    source = sourceSets.main.allJava
    classpath = sourceSets.main.runtimeClasspath
    title = "英方 Java SDK 文档"
    options {
        memberLevel = JavadocMemberLevel.PUBLIC
        setEncoding 'UTF-8'
        setWindowTitle "英方 Java SDK 文档"
    }
}

def versionName() {
    String config = getProjectDir().getPath() + '/src/main/java/com/i2soft/util/Constants.java'
    String fileContents = new File(config).text
    Matcher myMatcher = fileContents =~ /VERSION = "(.+)";/
    String version = myMatcher[0][1]
    println(version)
    return version
}

static def versionNameToCode(String version) {
    String v = version.replaceAll(/\./, '')
    return v.toLong()
}

String version = versionName()
int code = versionNameToCode(version)

setProperty('VERSION_NAME', version)
setProperty('VERSION_CODE', code)

apply from: 'mvn_push.gradle'

apply plugin: 'eclipse'

task gen_eclipse(dependsOn: [
        'cleanEclipseProject', 'cleanEclipseClasspath',
        'eclipseProject', 'eclipseClasspath'])
eclipseProject.mustRunAfter cleanEclipseProject
eclipseClasspath.mustRunAfter cleanEclipseClasspath